version: '3'
services:
  voter-db:
    build: postgres/.

  rabbit-mq:
    build: rabbitMq/.
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: voter
      RABBITMQ_DEFAULT_PASS: v0t3r