version: '3'
services:
  voter-db:
    build: ""

  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: voter
      RABBITMQ_DEFAULT_PASS: v0t3r